// اضافه‌کار در صفحه دستگاه (QR)
const {chromium}=require('playwright'); const http=require('http'), fs=require('fs'), path=require('path');
const HTML=fs.readFileSync(path.join(__dirname,'..','out.html'));
let fails=0; const ok=(c,m)=>{ console.log((c?'  ok  ':'  FAIL ')+m); if(!c) fails++; };
const sleep=ms=>new Promise(r=>setTimeout(r,ms)); const pad=n=>String(n).padStart(2,'0');
const hm=m=>{ m=((m%1440)+1440)%1440; return pad(Math.floor(m/60))+':'+pad(m%60); };
(async()=>{
  const web=http.createServer((q,r)=>{ r.writeHead(200,{'Content-Type':'text/html; charset=utf-8'}); r.end(HTML); }); await new Promise(r=>web.listen(0,r));
  const br=await chromium.launch({executablePath:process.env.CHROMIUM||undefined});
  async function boot(seed){ const c=await br.newContext({locale:'fa-IR',viewport:{width:390,height:844}}); const p=await c.newPage(); p.errs=[];
    p.on('pageerror',e=>p.errs.push(String(e))); p.on('dialog',d=>{ p.dlg=(p.dlg||0)+1; d.dismiss(); });
    await p.goto(`http://localhost:${web.address().port}/nt/s.html`); await p.waitForFunction(()=>window.ntSync&&window.ntNav,null,{timeout:15000});
    await p.addStyleTag({content:'.sydlg,.sybd{display:none!important}'});
    const jk=await p.evaluate(()=>todayKey()); const n=new Date(), nm=n.getHours()*60+n.getMinutes();
    await p.evaluate(([seed])=>{ Object.keys(seed).forEach(k=>localStorage.setItem(k,JSON.stringify(seed[k]))); window.ntLocked=false; document.body.classList.remove('ntlocked'); try{ ntBoot(); }catch(e){} },[seed(jk,nm)]);
    await p.waitForFunction(()=>{ try{ return !!frames[0].contentDocument.getElementById('flGrid'); }catch(e){ return false; } },null,{timeout:15000});
    await sleep(700); return p; }

  const dlg=p=>p.evaluate(()=>{ const d=document.getElementById('ntQrDlg'); return d&&!d.hidden?d.innerText.replace(/\s+/g,' '):''; });
  const openDev=async(p,n)=>{ await p.evaluate(n=>{ frames[0].contentDocument.querySelector('.fld[data-dev*="'+n+'"]').click(); },n); await sleep(700); };
  const fill=(p,id,v)=>p.evaluate(([id,v])=>{ const e=document.getElementById(id); e.value=v; },[id,v]);
  const click=async(p,id)=>{ await p.evaluate(id=>document.getElementById(id).click(),id); await sleep(500); };
  const wk=p=>p.evaluate(()=>{ const db=JSON.parse(localStorage.getItem('nt_tavaqof_v1')||'{}'); const o=[]; Object.keys(db).forEach(k=>{ if(k.split('|')[1]==='اضافه') (db[k].work||[]).forEach(w=>o.push({k,...w})); }); return o; });
  console.log('1) شروع و پایان اضافه‌کار');
  const P=await boot((jk,nm)=>({nt_tavaqof_v1:{}}));
  await P.evaluate(()=>{ ntStops.HOURS={from:0,to:1}; window.__jk=frames[0].contentWindow.todayKey(); frames[0].contentWindow.postMessage({nt:'show'},'*'); }); await sleep(500);
  await openDev(P,'TRS01');
  let d=await dlg(P); ok(/اضافه‌کار.*در جریان نیست/.test(d) && /شروع اضافه‌کار/.test(d),'دکمه «شروع اضافه‌کار» و وضعیت: '+d.slice(0,120));
  await click(P,'qrWStart');
  ok(/شروع اضافه‌کار/.test(await dlg(P)) && await P.evaluate(()=>/^\d\d:\d\d$/.test(document.getElementById('qrFrom').value)),'فرم باز شد و ساعت شروع پیش‌فرض «اکنون» است');
  await fill(P,'qrFrom','25:00'); await click(P,'qrSave');
  ok(/ساعت شروع را مثل/.test(await dlg(P)) && (await wk(P)).length===0,'ساعت نادرست رد شد');
  await fill(P,'qrFrom','15:30'); await fill(P,'qrDay','۱۴۰۵/۷/۱۹'); await click(P,'qrSave');
  let W=await wk(P);
  ok(W.length===1 && W[0].k==='1405/07/19|اضافه' && W[0].from==='15:30' && W[0].to==='' && W[0].dev==='کامیون TRS01','ثبت شد: کلید «۱۴۰۵/۰۷/۱۹|اضافه»، ارقام فارسی درست خوانده شد — '+JSON.stringify(W));
  d=await dlg(P); ok(/در جریان از ۱۵:۳۰/.test(d) && /پایان اضافه‌کار/.test(d),'صفحه دستگاه: در جریان از ۱۵:۳۰ و دکمه پایان');
  await click(P,'qrWEnd'); await fill(P,'qrTo','15:30'); await click(P,'qrSave');
  ok(/یکی است/.test(await dlg(P)),'پایان هم‌ساعت با شروع رد شد');
  await fill(P,'qrTo','18:10'); await click(P,'qrSave');
  W=await wk(P); ok(W.length===1 && W[0].to==='18:10','پایان ثبت شد (۱۸:۱۰)');
  ok(/اضافه‌کار.*در جریان نیست/.test(await dlg(P)),'بعد از پایان، دوباره «در جریان نیست»');
  console.log('2) ثبت یکجا (از فرم کاغذی) و جلوگیری از دوبار باز');
  await click(P,'qrWStart'); await fill(P,'qrDay','1405/07/18'); await fill(P,'qrFrom','22:00'); await fill(P,'qrTo','01:00'); await click(P,'qrSave');
  W=await wk(P); ok(W.length===2 && W.some(w=>w.k==='1405/07/18|اضافه' && w.from==='22:00' && w.to==='01:00'),'ثبت یکجا با شروع و پایان (از نیمه‌شب گذشت)');
  const mins=await P.evaluate(()=>ntStops.work('1405/07/01','1405/07/30').map(w=>w.min).join());
  ok(mins==='180,160' || mins==='160,180','ntStops.work: مدت‌ها ۱۸۰ و ۱۶۰ دقیقه — '+mins);
  await click(P,'qrWStart'); await fill(P,'qrDay','1405/07/19'); await fill(P,'qrFrom','19:00'); await fill(P,'qrTo',''); await click(P,'qrSave');
  ok(await P.evaluate(()=>!!document.getElementById('qrWEnd') && !document.getElementById('qrWStart')),'یک اضافه‌کار باز: دکمه فقط «پایان» است');
  console.log('3) فرم توقف شیفت رکورد اضافه‌کار را پاک نمی‌کند');
  await P.evaluate(()=>{ document.getElementById('ntQrDlg').hidden=true; });
  const kept=await P.evaluate(()=>{ const i=DOCS.findIndex(d=>d.name==='توقف شیفت'); show(i); return true; }); await sleep(800);
  await P.evaluate(()=>{ const f=frames[DOCS.findIndex(d=>d.name==='توقف شیفت')].contentWindow; try{ f.db['x|y']={stops:[]}; f.save(true); }catch(e){} });
  await sleep(300);
  ok((await wk(P)).length===3,'بعد از ذخیره در فرم توقف شیفت، اضافه‌کارها سر جایشان است');
  console.log('4) دستگاه غیر اصلی و دسترسی');
  const Q=await boot((jk,nm)=>({nt_tavaqof_v1:{}}));
  await Q.evaluate(()=>{ const dv=ntQr.DEVS.find(x=>!ntStops.tracked(x.name)); window.__o=dv.id; frames[0].contentWindow.parent.postMessage({nt:'qrdev',id:dv.id},'*'); }); await sleep(800);
  ok(!/شروع اضافه‌کار/.test(await dlg(Q)),'دستگاه غیر اصلی (ژنراتور و ...) دکمه اضافه‌کار ندارد');
  await Q.evaluate(()=>{ document.getElementById('ntQrDlg').hidden=true; });
  await Q.evaluate(()=>{ ntSync.canWriteTab=n=>n!=='توقف شیفت'; }); await openDev(Q,'TRS01');
  ok(!/شروع اضافه‌کار/.test(await dlg(Q)),'بدون اجازه نوشتن در «توقف شیفت»، دکمه اضافه‌کار نیست');
  ok(P.errs.length===0 && Q.errs.length===0,'بدون خطا '+P.errs.concat(Q.errs).slice(0,2).join('|'));
  await br.close(); web.close();
  console.log(fails?`\n${fails} آزمایش ناموفق`:'\nهمه موفق'); process.exit(fails?1:0);
})();
